JCF: DUNE-DAQ/daq-deliverables#73: merge the submodules in light of t…
DUNE-DAQ/detdataformats pull request #87
Opened 2023-05-09 21:14 UTC by jcfreeman2

…he detdataformats recent split

2023-05-10 07:09 UTC, alessandrothea approved these changes

2023-05-10 07:19 UTC, alessandrothea requested changes

2023-05-10 07:19 UTC, alessandrothea commented on pybindsrc/module.cpp
> +namespace dunedaq::detdataformats::python {
While we've been using extern register_*, it's not great from code/compilation perspective. I would keep the declaration of the register functions in a separate header, changing the name from submodules.hpp to something more appropriate, like registrators.hpp

2023-05-11 17:26 UTC, dingp approved these changes
LGTM

2023-05-11 17:27 UTC, merged